---
title: "Yohan Alexander's CV"
author: Yohan Alexander
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['../css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis',
  echo = FALSE
)

library(glue)
library(tidyverse)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that are inserted for placement at the end
links <- c()

source('../parsing_functions.R') # Functions for building sections from CSV data
source('common_variables-br.R')  # Small variables for non-csv data such as intro text

# Load csv with position info
position_data <- read_csv('positions-br.csv')
```

```{r}
# When in export mode the little dots are unaligned, so fix that.
if(PDF_EXPORT){
  cat("
  <style>
  :root{
    --decorator-outer-offset-left: -6.5px;
  }
  </style>")
}
```

Aside
================================================================================

CONTATO {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> yohanfranca@gmail.com
- <i class="fa fa-linkedin"></i> [yohanalexander](http://linkedin.com/in/yohanalexander)
- <i class="fa fa-github"></i> [yohanalexander](http://github.com/yohanalexander)
- <i class="fa fa-instagram"></i> [yohanalexander](http://instagram.com/yohanalexander)
- <i class="fa fa-link"></i> [yohanalexander.github.io](http://yohanalexander.github.io/)
- <i class="fa fa-phone"></i> +55 (79) 99864-7553

IDIOMAS {#languages}
--------------------------------------------------------------------------------
```{r}
cat(sanitize_links(languages))
```

HABILIDADES {#skills}
--------------------------------------------------------------------------------
```{r}
cat(sanitize_links(skills))
```

FERRAMENTAS {#tools}
--------------------------------------------------------------------------------

```{r}
build_skill_bars(tools)
```

DISCLAIMER {#disclaimer}
--------------------------------------------------------------------------------

Construído com o pacote R [**pagedown**](https://github.com/rstudio/pagedown).

Atualizado em `r format(Sys.Date(), format="%d/%m/%Y")`.

Main
================================================================================

YOHAN ALEXANDER {#title}
--------------------------------------------------------------------------------
### <i class="fa fa-user" aria-hidden="true"></i> DESENVOLVEDOR FULL CYCLE

```{r}
cat(sanitize_links(intro_text))
```

EDUCAÇÃO {data-icon=graduation-cap}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'education')
```

PESQUISA CIENTÍFICA {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'research')
```

EXPERIÊNCIA PROFISSIONAL {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'industry')
```

<!--
PROJETOS {data-icon=archive}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'projects')
```

PUBLICAÇÕES {data-icon=file-text}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'publications')
```
-->

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

```{r}
if(PDF_EXPORT){
  cat("

Links {data-icon=link}
--------------------------------------------------------------------------------

<br>


")

  walk2(links, 1:length(links), function(link, index){
    print(glue('{index}. {link}'))
  })
}
```
