# Site settings
title: Yohan Alexander
description: Portfólio dos meus projetos
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yohanalexander.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yohan Alexander
user_description: Desenvolvedor Python e autodidata em ciência de dados e machine learning.
user_title: Data Scientist
email: yohanfranca@gmail.com
# twitter_username: lorem_ipsum
github_username:  yohanalexander
# gplus_username:  lorem_ipsum
instagram: yohanalexander
logo_path: "/assets/img/signo.png"

# Google-analytics
google-analytics:
  id: "UA-156934758-1"

exclude: ['package.json', 'src' , 'node_modules']
plugins_dir:
  - jekyll-redirect-from