# Site settings
title: Yohan Alexander
description: My Portfolio and Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yohanalexander.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yohan Alexander
user_description: Sou um desenvolvedor autodidata apaixonado pelo ecossistema Python, com experiência no uso de diversas bibliotecas como Numpy, Pandas, Matplotlib, Jupyter, Scikit learn, Seaborn, Plotly, Tensorflow, Keras, e Django.
user_title: Desenvolvedor Python
email: yohanfranca@gmail.com
# twitter_username: lorem_ipsum
github_username:  yohanalexander
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "gYJ56k3J-uhuRPtdbYwETbcULRwIsJSQ3naerXM5Fk8"

exclude: ['package.json', 'src' , 'node_modules']
